import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import "react-multi-carousel/lib/styles.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="dark:text-white w-full grain h-20 flex justify-between items-center p-4 lg:px-16 xl:px-32 bg-text bg-opacity-80 backdrop-blur-md text-background backdrop-blur-md sticky top-0 z-50 transition-all duration-700 shadow-lg">
          <div className="flex-1">
            <Link href={"/"} className="btn btn-ghost text-xl">WAsHub</Link>
          </div>

          <div className="hidden lg:flex flex-none">
            <ul className="menu menu-horizontal px-1">
              <li><Link href={"/resources"}>Resources</Link></li>
              <li><Link href={"/about"}>About</Link></li>
              <li><Link href={"/references"}>References</Link></li>
            </ul>
          </div>

          <div className="lg:hidden dropdown dropdown-end">
            <button className="btn btn-square btn-ghost">
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" className="inline-block h-5 w-5 stroke-current"> <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M4 6h16M4 12h16M4 18h16"></path> </svg>
            </button>
            <ul className="dropdown-content menu bg-base-100 rounded-box z-1 w-52 p-2 shadow-sm">
              <li><Link href={"/resources"}>Resources</Link></li>
              <li><Link href={"/about"}>About</Link></li>
              <li><Link href={"/references"}>References</Link></li>
            </ul>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
